# server port : 9099
server:
  port: 9099

spring:
  application:
    name: demo9

  devtools:
    restart:
      enabled: true
    livereload:
      enabled: true

  thymeleaf:
    cache: false

  # Database Setting(datasource)
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/springgroup
    username: root
    password: 1234

  # JPA Setting
  jpa:
    open-in-view: true
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.CamelCaseToUnderscoresNamingStrategy
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect

  # Security Default User (for test)
  security:
    user:
      name: admin@green.com
      password: 1234

  # File upload MaxSize Setting
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 30MB

  # ✅ Static resource mapping 추가 (ckeditorUpload 경로를 정적 리소스로 등록)
  web:
    resources:
      static-locations:
        - classpath:/static/
        - file:src/main/webapp/

# Log information Setting
logging:
  level:
    org:
      hibernate:
        type:
          descriptor:
            sql: trace
